# Generated by Django 2.2 on 2019-05-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0004_auto_20190501_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingminutes',
            old_name='meetingtitle',
            new_name='meetingid',
        ),
    ]
