# Generated by Django 2.2 on 2019-05-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0005_auto_20190501_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='durationid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
