# Generated by Django 2.2 on 2019-04-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_auto_20190405_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resourcetype',
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourcedescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
